#pragma checksum "..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F925DB08E133241A871B756B3D757C05E5FD8C22"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 47 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox spamTextBox;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Run SpamTextBox;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox iterationsTextBox;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Run IterationsTextBox;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton iterationsUp;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton iterationsDown;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox intervalTextBox;
        
        #line default
        #line hidden
        
        
        #line 147 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Run IntervalTextBox;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton intervalUp;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton intervalDown;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox intervalType;
        
        #line default
        #line hidden
        
        
        #line 185 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBoxItem interval_lb_ms;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBoxItem interval_lb_sec;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBoxItem interval_lb_min;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox waitBeforeStartTextBox;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Run WaitBeforeStartTextBox;
        
        #line default
        #line hidden
        
        
        #line 218 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton WaitUp;
        
        #line default
        #line hidden
        
        
        #line 229 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton waitDown;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox WaitBeforeStartType;
        
        #line default
        #line hidden
        
        
        #line 248 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBoxItem wait_lb_ms;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBoxItem wait_lb_sec;
        
        #line default
        #line hidden
        
        
        #line 250 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBoxItem wait_lb_min;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button startSpamBtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 7 "..\..\..\MainWindow.xaml"
            ((WpfApp1.MainWindow)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 49 "..\..\..\MainWindow.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.spamTextBox = ((System.Windows.Controls.RichTextBox)(target));
            return;
            case 4:
            this.SpamTextBox = ((System.Windows.Documents.Run)(target));
            return;
            case 5:
            this.iterationsTextBox = ((System.Windows.Controls.RichTextBox)(target));
            
            #line 89 "..\..\..\MainWindow.xaml"
            this.iterationsTextBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberTextBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 6:
            this.IterationsTextBox = ((System.Windows.Documents.Run)(target));
            return;
            case 7:
            this.iterationsUp = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 108 "..\..\..\MainWindow.xaml"
            this.iterationsUp.Click += new System.Windows.RoutedEventHandler(this.iterationsUp_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.iterationsDown = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 119 "..\..\..\MainWindow.xaml"
            this.iterationsDown.Click += new System.Windows.RoutedEventHandler(this.iterationsDown_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.intervalTextBox = ((System.Windows.Controls.RichTextBox)(target));
            
            #line 138 "..\..\..\MainWindow.xaml"
            this.intervalTextBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberTextBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 10:
            this.IntervalTextBox = ((System.Windows.Documents.Run)(target));
            return;
            case 11:
            this.intervalUp = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 155 "..\..\..\MainWindow.xaml"
            this.intervalUp.Click += new System.Windows.RoutedEventHandler(this.intervalUp_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.intervalDown = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 166 "..\..\..\MainWindow.xaml"
            this.intervalDown.Click += new System.Windows.RoutedEventHandler(this.intervalDown_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.intervalType = ((System.Windows.Controls.ListBox)(target));
            return;
            case 14:
            this.interval_lb_ms = ((System.Windows.Controls.ListBoxItem)(target));
            return;
            case 15:
            this.interval_lb_sec = ((System.Windows.Controls.ListBoxItem)(target));
            return;
            case 16:
            this.interval_lb_min = ((System.Windows.Controls.ListBoxItem)(target));
            return;
            case 17:
            this.waitBeforeStartTextBox = ((System.Windows.Controls.RichTextBox)(target));
            
            #line 201 "..\..\..\MainWindow.xaml"
            this.waitBeforeStartTextBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.NumberTextBox_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 18:
            this.WaitBeforeStartTextBox = ((System.Windows.Documents.Run)(target));
            return;
            case 19:
            this.WaitUp = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 218 "..\..\..\MainWindow.xaml"
            this.WaitUp.Click += new System.Windows.RoutedEventHandler(this.WaitUp_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.waitDown = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 229 "..\..\..\MainWindow.xaml"
            this.waitDown.Click += new System.Windows.RoutedEventHandler(this.waitDown_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.WaitBeforeStartType = ((System.Windows.Controls.ListBox)(target));
            return;
            case 22:
            this.wait_lb_ms = ((System.Windows.Controls.ListBoxItem)(target));
            return;
            case 23:
            this.wait_lb_sec = ((System.Windows.Controls.ListBoxItem)(target));
            return;
            case 24:
            this.wait_lb_min = ((System.Windows.Controls.ListBoxItem)(target));
            return;
            case 25:
            this.startSpamBtn = ((System.Windows.Controls.Button)(target));
            
            #line 258 "..\..\..\MainWindow.xaml"
            this.startSpamBtn.Click += new System.Windows.RoutedEventHandler(this.startSpam_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

